title: Training materials
title_url: /training_materials
subitems:
<<<<<<< HEAD
  _ title: RDMbites
  - description: short informative videos (3_5 minutes) to describe basic and specialised aspects of RDM
    url: /rdmbites
    image_url: /assets/img/icons/rdmbites_icon.svg
    subitems:
      - title: Sequencing data
        url: /seq_data_collection
      - title: Data Management Essentials Collection
        url: /data_management_essentials_collection
      - title: Data Protection Collection
        url: /data_protection_collection
      - title: Data Sharing Collection
        url: /data_sharing_collection
      - title: Data Storage Collection
        url: /data_storage_collection
      - title: REDCap collection
        url: /redcaap_collection
      - title: Sensitive data collection
=======
  - title: RDMbites
    description: short informative videos (3_5 minutes) to describe basic and specialised aspects of RDM
    url: /rdmbites
    image_url: /assets/img/icons/rdmbites_icon.svg
    subitems:
      - title: Bioimage
        url: /bioimage_collection
      - title: Data management essentials collection
        url: /data_management_essentials_collection
      - title: Data protection collection
        url: /data_protection_collection
      - title: Data sharing collection
        url: /data_sharing_collection
      - title: Data storage collection
        url: /data_storage_collection
      - title: REDCap collection
        url: /redcap_collection
      - title: Sensitive data collection
        url: /seq_data_collection
      - title: Sequencing data collection
>>>>>>> f7145f07545f8d4c9f1bf9357654338d6bb35d7a
        url: /sensitive_data_collection
  - title: Course materials
    description: course materials open to the entire research community on basic and specialised aspects of RDM
    url: /course_materials
    image_url: /assets/img/icons/course_materials_icon.svg
    subitems:
      - title: Bioimage metadata course
        url: /bioimage_metadata_course
      - title: Introdcution to cBioPortal
        url: /cbioportal
      - title: FAIR pointers course
        url: /fair_pointers_course
      - title: FAIRification of an RNAseq dataset
        url: /fairification_rnaseq_course
  - title: Recommended resources
<<<<<<< HEAD
    description: course materials open to the entire research community on basic and specialised aspects of RDM
=======
    description: curated list of recommended materials on RDM
>>>>>>> f7145f07545f8d4c9f1bf9357654338d6bb35d7a
    url: /recommended_resources
    image_url: /assets/img/icons/course_materials_icon.svg