title: Training materials
title_url: /training_materials
subitems:
  _ title: RDMbites
  - description: short informative videos (3_5 minutes) to describe basic and specialised aspects of RDM
    url: /rdmbites
    image_url: /assets/img/icons/rdmbites_icon.svg
    subitems:
      - title: Sequencing data
        url: /seq_data_collection
      - title: Data Management Essentials Collection
        url: /data_management_essentials_collection
      - title: Data Protection Collection
        url: /data_protection_collection
      - title: Data Sharing Collection
        url: /data_sharing_collection
      - title: Data Storage Collection
        url: /data_storage_collection
      - title: REDCap collection
        url: /redcaap_collection
      - title: Sensitive data collection
        url: /sensitive_data_collection
  - title: Course materials
    description: course materials open to the entire research community on basic and specialised aspects of RDM
    url: /course_materials
    image_url: /assets/img/icons/course_materials_icon.svg
    subitems:
      - title: cBioPortal workshop
        url: /cbioportal
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_2
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_3
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_4
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_5
  - title: Recommended resources
    description: course materials open to the entire research community on basic and specialised aspects of RDM
    url: /recommended_resources
    image_url: /assets/img/icons/course_materials_icon.svg