title: Training materials
title_url: /training_materials
subitems:
  - title: RDMbites
    description: short informative videos (3-5 minutes) to describe basic and specialised aspects of RDM
    url: /rdmbites
    image_url: /assets/img/icons/rdmbites-icon.svg
    subitems:
      - title: Sequencing data
        url: /seq-data-collection
      - title: Data Management Essentials Collection
        url: /data-management-essentials-collection
      - title: Data Protection Collection
        url: /data-protection-collection
      - title: Data Sharing Collection
        url: /data-sharing-collection
      - title: Data Storage Collection
        url: /data-storage-collection
      - title: REDCap collection
        url: /redcaap-collection
      - title: Sensitive data collection
        url: /sensitive-data-collection
  - title: Course materials
    description: course materials open to the entire research community on basic and specialised aspects of RDM
    url: /course-materials
    image_url: /assets/img/icons/course-materials-icon.svg
    subitems:
      - title: cBioPortal workshop
        url: /cbioportal
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_2
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_3
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_4
      - title: Name of course (with links to Carpentries/GTN)
        url: /course_name_5
  - title: Recommended resources
    description: course materials open to the entire research community on basic and specialised aspects of RDM
    url: /recommended-resources
    image_url: /assets/img/icons/course-materials-icon.svg
    subitems:
      - title: 
     
