title: ELIXIR-UK Fellowship
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "A Fellowship of UK ambassadors to build capacity in RDM for the life sciences"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.21.0

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md

defaults:
  -
    scope:
      path: "pages/events/TEMPLATE_event.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/training_materials/rdmbites/TEMPLATE_collection.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/training_materials/course_materials/TEMPLATE_course.md"
      type: "pages"
    values:
      sitemap: false
      sidebar: 
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/training_materials/recommended_resources/TEMPLATE_course.md"
      type: "pages"
    values:
      sitemap: false
      sidebar: 
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/events"
    values:
      type: events
      datatable: false
      sidebar: events
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/training_materials"
    values:
      sidebar: training_materials
  -
    scope:
      path: "pages/training_materials/rdmbites"
    values:
      sidebar: rdmbites
  -
    scope:
      path: "pages/training_materials/course_materials"
    values:
      sidebar: course_materials
  -
    scope:
      path: "pages/training_materials/recommended_resources"
    values:
      sidebar: recommended_resources
      

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
