title: RDMkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "Best practices and guidelines you can use for FAIR management of your research data."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.21.0

sass:
  style: compressed
  sourcemap: never

gtag: G-RXQ55EFTTH
# Google analytics tag

dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: data_management
      search_exclude: false
  -
    scope:
      path: "pages/data_life_cycle/TEMPLATE_rdm_cycle.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/national_resources/TEMPLATE_resources.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/tool_assembly/TEMPLATE_tool_assembly.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_domain/TEMPLATE_your_domain.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_role/TEMPLATE_your_role.md"
     # type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your_tasks/TEMPLATE_your_tasks.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/data_life_cycle"
    values:
      type: data_life_cycle
  -
    scope:
      path: "pages/your_domain"
    values:
      type: your_domain
  -
    scope:
      path: "pages/your_tasks"
    values:
      type: your_tasks
  -
    scope:
      path: "pages/your_role"
    values:
      type: your_role
  -
    scope:
      path: "pages/tool_assembly"
    values:
      type: tool_assembly
  -
    scope:
      path: "pages/national_resources"
    values:
      type: national_resources
      datatable: true
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
