title: RDMkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "Best practices and guidelines you can use for FAIR management of your research data."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.21.0

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: training_materials
      search_exclude: false
  -
    scope:
      path: "pages/events/TEMPLATE_event.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/rdmbites/TEMPLATE_collection.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/course-materials/TEMPLATE_course.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  
  -
    scope:
      path: "pages/rdmbites"
    values:
      type: rdmbites
      datatable: false
  -
    scope:
      path: "pages/events"
    values:
      type: events
      datatable: false
  -
    scope:
      path: "pages/course-materials"
    values:
      type: course_materials
      datatable: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
